pipeline{
  agent any
  tools{
    maven 'maven_3.9.2'
  }
  stages{
    stage ("Clonado del repositorio"){
      steps{
        git branch: "develop" , url: "https://github.com/mvazgon/curso_jenkins_maven.git"
      }
    }
    stage ("Goals Maven"){
      steps{
        sh """
          cd Ejercicio_5
          mvn clean install
          mvn test
          ls -lrtha *.war
        """
      }
    }
    stage ("Movemos el producto renombrandolo"){
      steps{
        echo "aqui tenemos que mover"
      }
    }
  }
  post{
    success{
      echo "Lo logramos"
    }
    failure{
      echo "Fallamos"
    }
  }
}
